# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_rating', models.CharField(max_length=20)),
                ('movie_plot', models.CharField(max_length=10000)),
                ('movie_earn', models.CharField(max_length=20)),
                ('movie_poster', models.CharField(max_length=1000)),
                ('movie_year', models.CharField(max_length=10)),
                ('movie_director', models.CharField(max_length=1000)),
                ('movie_runtime', models.CharField(max_length=15)),
                ('movie_stars', models.CharField(max_length=1500)),
            ],
        ),
    ]
