# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPref',
            new_name='MovieInfo',
        ),
    ]
