# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_firstform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstform',
            name='user',
        ),
        migrations.DeleteModel(
            name='FirstForm',
        ),
    ]
