# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20180408_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='user_rating',
            field=models.BooleanField(default=False),
        ),
    ]
