# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_movieinfo_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='star1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='star2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='star3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='star4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='star5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='user_rating',
            field=models.IntegerField(max_length=6),
        ),
    ]
