# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_auto_20180409_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='user_rating',
            field=models.IntegerField(),
        ),
    ]
